#!/bin/bash
#add a test to sqlserver
read -p "please input mysql's username:" username
read -p "please input mysql's password:" password
mysql -u$username -p$password < test.sql

tar -xvf apr-1.5.1.tar.gz
tar -xvf apr-util-1.5.4.tar.gz
#configure make and install apr
cd apr-1.5.1
./configure --prefix=/usr/local
make clean
make
make install
cd ..

#configure make and install apr-util
cd apr-util-1.5.4
./configure --prefix=/usr/local --with-apr=/usr/local --with-mysql
make
make install
cd ..

#make and install authServer
make clean
make
make install

rm -rf apr-util-1.5.4 apr-1.5.1
echo install finished

